
.PHONY: start test
VENV = .venv

start:
	. $(VENV)/bin/activate

11: start
	pytest 11/tests.py -v

36: start
	pytest 36/tests.py -v

42: start
	pytest 42/tests.py -v

128: start
	pytest 128/tests.py -v

153: start
	pytest 153/tests.py -v

167: start
	pytest 167/tests.py -v

238: start
	pytest 238/tests.py -v

347: start
	pytest 347/tests.py -v
	
424: start
	pytest 424/tests.py -v
